Redhat WIP

diff --git a/Dockerfile.redhat b/Dockerfile.redhat
--- a/Dockerfile.redhat
+++ b/Dockerfile.redhat
@@ -208,6 +208,52 @@ RUN yum install -y http://vault.centos.org/centos/8-stream/PowerTools/x86_64/os/
     rm -rf /var/cache/yum
 RUN if [ -f /opt/intel/openvino/samples/cpp/build_samples.sh ];  then /opt/intel/openvino/samples/cpp/build_samples.sh ; fi
 #################### END OF OPENVINO BINARY INSTALL
+### gpu drivers for gpu gtest begin
+RUN dnf upgrade --setopt=install_weak_deps=0 -y ; \
+    dnf install -y pkg-config && rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/tbb-2018.2-9.el8.x86_64.rpm && \
+    case $INSTALL_DRIVER_VERSION in \
+    "23.22.26516") \
+            dnf install -y libedit ; \
+            rpm -ivh https://repositories.intel.com/gpu/rhel/8.6/pool/i/intel-gmmlib-22.3.7-i678.el8_6.x86_64.rpm ; \
+            rpm -ivh https://repositories.intel.com/gpu/rhel/8.6/pool/i/intel-igc-core-1.0.14062.14-682.el8_6.x86_64.rpm ; \
+            rpm -ivh https://repositories.intel.com/gpu/rhel/8.6/pool/i/intel-igc-opencl-1.0.14062.14-682.el8_6.x86_64.rpm ; \
+            rpm -ivh https://repositories.intel.com/gpu/rhel/8.6/pool/i/intel-opencl-23.22.26516.25-682.el8_6.x86_64.rpm ; \
+            rpm -ivh https://repositories.intel.com/gpu/rhel/8.6/pool/i/intel-level-zero-gpu-1.3.26516.25-682.el8_6.x86_64.rpm ; \
+            rpm -ivh https://repositories.intel.com/gpu/rhel/8.6/pool/l/level-zero-1.11.0-674.el8_6.x86_64.rpm ; \
+    ;; \
+
+            *) \
+            echo "ERROR: Unrecognized driver ${INSTALL_DRIVER_VERSION}." ; \
+            exit 1 ; \
+    esac ; \
+    echo "Installed opencl driver version:" ;\
+    echo `rpm -qa | grep intel-opencl` ; \
+    
+    if [ "$INSTALL_RPMS_FROM_URL" == "" ] ; then \
+            rpm -ivh http://vault.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm; \
+    else  \
+            dnf install -y tar gzip; \
+            mkdir /tmp_ovms ; \
+            cd /tmp_ovms ; \
+            curl -L --fail -o deps.tar.xz "$INSTALL_RPMS_FROM_URL" ; \
+            tar -xf deps.tar.xz ; \
+            ls -Rahl . ; \
+            rpm -vi pkg/bin/*.rpm ; \
+            cd / ; \
+            rm -rf /tmp_ovms ; \
+            dnf remove -y tar gzip; \
+    fi ; \
+    # For image with Python enabled install Python library
+    if ! [[ $debug_bazel_flags == *"PYTHON_DISABLE=1"* ]]; then \
+        dnf install -y python39-libs --setopt=install_weak_deps=0; \
+        mkdir -p /ovms/lib/openvino-2024.3.dist-info && \
+        echo $'Metadata-Version: 1.0\nName: openvino\nVersion: 2024.3' > /ovms/lib/openvino-2024.3.dist-info/METADATA ; \
+    fi ; \
+    dnf install -y shadow-utils; \
+    cp -v /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt ; \
+    groupadd --gid 5000 ovms && groupadd --gid 44 video1 && \
+    useradd --home-dir /home/ovms --create-home --uid 5000 --gid 5000 --groups 39,44 --shell /bin/bash --skel /dev/null ovms
+### gpu drivers for gpu gtest end
 
 # OpenVINO Tokenizers extension
 ENV OpenVINO_DIR=/opt/intel/openvino/runtime/cmake
